version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    ports:
      - "0.0.0.0:9200:9200"
    volumes:
      - ./elasticserach.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
      - ./docker-data-volumes/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk-network

  logstash:
    image: logstash:7.16.2
    environment:
      - XPACK_MONITORING_ENABLED=false
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:5044:5044"
    volumes:
      - ./logstash.conf/:/usr/share/logstash/pipeline/logstash.conf/:ro
    networks:
      - elk-network

  kibana:
    image: kibana:7.16.2
    environment:
      - ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
    depends_on:
      - logstash
    ports:
      - "0.0.0.0:5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk-network

networks:
  elk-network:
